---
title: "Target Gene Enrichment Report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
 rmdformats::readthedown:
    toc_depth: 3
    code_folding: hide
    number_sections: true
---

```{r}
#set lib_folder to the folder where you put the enrichmentByClusterProfiler.R, gene_exp_functions.R, tissue_spec_functions.R, 
#pathway.Rmd, gene_exp.Rmd and tissue_specificity.Rmd
#you can set it as a local folder or a github folder
#set as a local folder would be easier for you to debug/modify the pipeline Rmd files
#set as a github folder would be easier for you to distribute the final Rmd file
#lib_folder="https://raw.githubusercontent.com/shengqh/ngsperl/master/lib"
lib_folder="/nobackup/h_cqs/shengq2/program/ngsperl/lib"
```

```{r,eval=FALSE,echo=FALSE}
#Example to render report
#set root_dir to the folder where you want to put this file "example.Rmd"

library(xfun)
root_dir = '/nobackup/h_cqs/shengq2/temp/tissue_enrichment_report'
dir.create(root_dir, showWarnings=FALSE)

setwd(root_dir)

copy_or_download<-function(source){
  target = paste0("./", basename(source))
  if(file.exists(source)){
    file.copy(source, target, overwrite=TRUE)
  }else{
    if(file.exists(target)){      
      file.remove(target)
    }
    download.file(source, target, "auto")
  }
}

copy_or_download("/nobackup/h_cqs/shengq2/program/cqsperl/examples/tissue_enrichment/example.Rmd")

copy_or_download(paste0(lib_folder, "/Report/pathway.Rmd"))
copy_or_download(paste0(lib_folder, "/Report/gene_exp.Rmd"))
copy_or_download(paste0(lib_folder, "/Report/tissue_specificity.Rmd"))

date_str = format(Sys.time(), "%Y%m%d")

xfun::Rscript_call(
  rmarkdown::render,
  list(input="example.Rmd",
       output_file=paste0(date_str, "_example.html"))
)
```

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
root_dir = '/nobackup/h_cqs/shengq2/temp/tissue_enrichment_report'

library(knitr)
library(data.table)
library(dplyr)

knitr::opts_chunk$set(
  include=TRUE, 
  echo=FALSE, 
  warning=FALSE, 
  message=FALSE, 
  results="asis"
)

date_str = format(Sys.time(), "%Y%m%d")

knitr::opts_knit$set(root.dir = root_dir)
setwd(root_dir)
```

```{r include=FALSE}
#pathway analysis
perform_pathway = T
if(perform_pathway){
  pathway_analysis_sets = c("KEGG", "Reactome", "WikiPathways")
  pathway_toType = "ENTREZID" #pathway analysis db ids
  organism="hsa" #"mmu"
  OrgDb="org.Hs.eg.db" #"org.Mm.eg.db"
}

#tissue specificity by protein atlas
perform_tissue_specificity = T
if(perform_tissue_specificity){
  proteinAtlasDatabaseFile = "/nobackup/h_cqs/references/tissue_specific/proteinatlas.tsv.zip"
  database_gene = "ENSEMBL" #What gene annotation is in the gene_exp file
  colNameGenes = "EntrezGeneSymbol"
  horizontalHeatmap=FALSE
}

#gene expression heatmap by tabula 
perform_gene_exp_heatmap = T
if(perform_gene_exp_heatmap){
  gene_exp_file = "/nobackup/h_cqs/references/tissue_specific/20230627_tabula_logNorm_averageExpression_matrix_by_tissueOnly.txt.gz"
  gene_exp_toType = "ENSEMBL" #pathway analysis db ids
  organism="hsa" #"mmu"
  OrgDb="org.Hs.eg.db" #"org.Mm.eg.db"

  perform_gene_exp_5perc=TRUE
  draw_gene_exp_heatmap_5perc_global=TRUE
}

#perform_singscore = F

test_bottom=FALSE
```

# Top 500 genes

```{r, eval=TRUE}
rnk_file="/nobackup/h_cqs/shengq2/program/cqsperl/data/Cardiomyocyte.AS_vs_Control_GSEA.rnk"
background_genes=fread(rnk_file)$V1
target_genes=background_genes[1:500]

#let's test background_genes=NULL
background_genes=NULL

#for each gene set, we need a new prefix and indicate the fromType
prefix="top500"
fromType = "SYMBOL" #target and background genes
```

```{r child="pathway.Rmd", eval=perform_pathway}
```

```{r child="tissue_specificity.Rmd", eval=perform_tissue_specificity}
```

```{r child="gene_exp.Rmd", eval=perform_gene_exp_heatmap}
```

```{r, eval=test_bottom}
cat("\n\n# Bottom 500\n\n")
background_genes=fread(rnk_file)$V1
target_genes=background_genes[(length(background_genes)-500): length(background_genes)]

#let's test 
background_genes=NULL

#for each gene set, we need a new prefix and indicate the fromType
prefix="bottom500"
fromType = "SYMBOL" #target and background genes
```

```{r child="pathway.Rmd", eval=perform_pathway & test_bottom}
```

```{r child="tissue_specificity.Rmd", eval=perform_tissue_specificity & test_bottom}
```

```{r child="gene_exp.Rmd", eval=perform_gene_exp_heatmap & test_bottom}
```

# Save the session information

```{r}
writeLines(capture.output(sessionInfo()), paste0(prefix, '.sessionInfo.txt'))
```

