#!/bin/bash

host=$(echo $HOSTNAME | cut -d'.' -f1)
lib_path="/nobackup/h_cqs/perl5/perl5_lib_${host}"
if( [ ! -d $lib_path ] ) 
then
  mkdir -p $lib_path
fi

echo "Install perl modules to $lib_path"

curl -L http://cpanmin.us | perl - -l $lib_path $1 $2 $3


